dataset:
  dset: FashionMNIST
  is_within_dset: true
  ind:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  ood:
  - 8
  - 9
path:
  root_dir: checkpoint/
  pretrained_dir: checkpoint/pretrained/
  sample_dir: checkpoint/OOD-Sample/
experiment:
  method: OOD-GAN
  regime: Balanced
  observed_cls: null
dset_info:
  img_info:
    H: 28
    W: 28
    C: 1
  num_class: 8
model:
  D: DenseNet
  D_config:
    depth: 100
  G: Deep_G
  G_config:
    noise_dim: 96
train_config:
  score: Wasserstein
  mc: 1
  T: 1
  max_epochs: 16
  bsz_tri: 64
  bsz_val: 64
  ood_bsz: 32
  optimizer:
    d_lr: 0.001
    g_lr: 0.001
    beta1: 0.5
    beta2: 0.999
  hp:
    ce: 1
    wass: 10
    dist: 1
  scaling: 0.001
  d_step_ratio: 1
  g_step_ratio: 1
  noise_dim: 96
  logging:
    n_steps_log: 20
    n_epochs_save: 4
eval_config:
  each_cls: false
  cls_idx:
  - 8
  - 9
  n_lr: 5000
