dataset:
  dset: CIFAR100-iNaturalist
  is_within_dset: False
  ind: [0, 1, 2, 3, 4, 5, 6, 7]
  ood: [8, 9]

path:
  sample_dir: ../checkpoint/OOD-Sample/

experiment:
  # regime: Balanced
  # observed_cls: null
  regime: Imbalanced
  observed_cls: [0]
