dataset:
  dset: FashionMNIST
  is_within_dset: True
  ind: [0, 1, 2, 3, 4, 5, 6, 7]
  ood: [8, 9]

path:
  root_dir: ../checkpoint/
  pretrained_dir: ../checkpoint/pretrained/

experiment:
  method: OOD-GAN
  regime: Balanced
  observed_cls: null

n_ood: 256

dset_info:
  img_info:
    H: 28
    W: 28
    C: 1
  num_class: 8

model:
  # D: "DenseNet"
  # D_config:
  #   depth: 100
  D: "DC_D"
  D_config: null
  G: "DC_CG"
  G_config:
    noise_dim: 96

train_config:
  mc: 2
  max_epochs: 3
  bsz_tri: 50
  bsz_val: 256 # this is used for evaluation
  optimizer:
    lr: 0.001
    beta1: 0.9 # this is the default value used in WOOD
    beta2: 0.999
  hp:
    ce: 1
    wass: 0.1
    dist: 1
  gd_step_ratio: 1
  noise_dim: 96
  logging:
    n_steps_log: 10

eval_config:
  each_cls: False
  cls_idx: [8, 9]
  n_lr: 5000
