dataset:
  dset: SVHN
  is_within_dset: True
  ind: [0, 1, 2, 3, 4, 5, 6, 7]
  ood: [8, 9]

path:
  root_dir: ../checkpoint/
  pretrained_dir: ../checkpoint/pretrained/

experiment:
  method: OOD-GAN
  regime: Balanced
  observed_cls: null

n_ood: 8

dset_info:
  img_info:
    H: 32
    W: 32
    C: 3
  num_class: 8

model:
  D: "DenseNet"
  D_config:
    depth: 100
  # D: "DC_D"
  # D_config: null
  G: "Deep_G"
  G_config:
    noise_dim: 96

train_config:
  mc: 3
  max_epochs: 4
  bsz_tri: 50
  bsz_val: 64 # this is used for evaluation
  optimizer:
    lr: 0.001
    beta1: 0.9 # this is the default value used in WOOD
    beta2: 0.999
  hp:
    ce: 1
    wass: 0.1
    dist: 1 # Set to zero to check whether this is important
  gd_step_ratio: 1
  noise_dim: 96
  logging:
    n_steps_log: 25

eval_config:
  each_cls: False
  cls_idx: [8, 9]
  n_lr: 5000
