dataset:
  dset: SVHN
  is_within_dset: True
  ind: [0, 1, 2, 3, 4, 5, 6, 7]
  ood: [8, 9]

path:
  root_dir: checkpoint/
  pretrained_dir: checkpoint/pretrained/
  sample_dir: /home/xysong/Out-of-Distribution-GANs/checkpoint/OOD-Sample/

experiment:
  method: OOD-GAN
  regime: Balanced
  observed_cls: null

n_ood: 512

dset_info:
  img_info:
    H: 32
    W: 32
    C: 3
  num_class: 8

model:
  D: "DenseNet"
  D_config:
    depth: 100
  G: "Deep_G"
  G_config:
    noise_dim: 96

train_config:
  # score: "Dynamic_Wasserstein"
  score: "Wasserstein"
  T: 1
  mc: 1
  max_epochs: 60
  bsz_tri: 64
  bsz_val: 64 # this is used for evaluation
  ood_bsz: 32
  optimizer:
    d_lr: 0.001
    g_lr: 0.001
    beta1: 0.5 # this is the default value used in WOOD
    beta2: 0.999
  hp:
    ce: 1
    wass: 0.1
    dist: 1 # Set to zero to check whether this is important
  scaling: 0.01
  d_step_ratio: 1
  g_step_ratio: 1
  noise_dim: 96
  logging:
    n_steps_log: 100
    n_epochs_save: 4

eval_config:
  each_cls: False
  cls_idx: [8, 9]
  n_lr: 5000
