dataset:
  dset: MNIST
  is_within_dset: True
  ind: [2, 3, 6, 8, 9]
  ood: [1, 7]

path:
  root_dir: ../checkpoint/
  pretrained_dir: ../checkpoint/pretrained/

experiment:
  method: OOD-GAN
  regime: Balanced
  observed_cls: null

n_ood: 1

dset_info:
  img_info:
    H: 28
    W: 28
    C: 1
  num_class: 5

# model:
#   D: "DC_D"
#   D_config: null
#   G: "DC_G"
#   G_config:
#     noise_dim: 96
model:
  D: "DenseNet"
  D_config:
    depth: 100
  # D: "DC_D"
  # D_config: null
  G: "Deep_G"
  G_config:
    noise_dim: 96

train_config:
  mc: 3
  max_epochs: 4
  bsz_tri: 50
  bsz_val: 64 # this is not used in general
  hp:
    ce: 1
    wass: 0.1
    dist: 1
  gd_step_ratio: 1
  noise_dim: 96
  optimizer:
    lr: 0.001
    beta1: 0.9
    beta2: 0.999
  logging:
    n_steps_log: 5

eval_config:
  each_cls: False
  cls_idx: [1, 7]
  n_lr: 5000
