dataset:
  dset: FashionMNIST
  is_within_dset: True
  ind: [0, 1, 2, 3, 4, 5, 6, 7]
  ood: [8, 9]

path:
  root_dir: checkpoint/
  pretrained_dir: checkpoint/pretrained/
  sample_dir: checkpoint/OOD-Sample/

experiment:
  method: WOOD
  regime: Balanced
  observed_cls: null

model:
  D: "DenseNet"
  D_config:
    depth: 100
  # D: DC_D
  # D_config: null
  G: null
  G_config: null

dset_info:
  img_info:
    H: 28
    W: 28
    C: 1
  num_class: 8

train_config:
  mc: 3
  max_epochs: 80
  bsz_tri: 64
  bsz_val: 64 # this is not used in general
  beta: 0.01 # WOOD balancing factor
  ood_bsz: 32
  optimizer:
    lr: 0.001
    beta1: 0.9
    beta2: 0.999

eval_config:
  each_cls: False
  cls_idx:
