dataset:
  dset: FashionMNIST
  is_within_dset: True
  ind: [0, 1, 2, 3, 4, 5, 6, 7]
  ood: [8, 9]

path:
  root_dir: ../checkpoint/
  pretrained_dir: ../checkpoint/pretrained/

experiment:
  method: WOOD
  regime: Balanced
  observed_cls: null

n_ood: 1

dset_info:
  img_info:
    H: 28
    W: 28
    C: 1
  num_class: 8

model:
  # D: "DenseNet"
  # D_config:
  #   depth: 100
  D: DC_D
  D_config:
    depth: 100
  G: null
  G_config: null

train_config:
  mc: 5
  max_epochs: 1
  bsz_tri: 50
  bsz_val: 256 # this is not used in general
  optimizer:
    lr: 0.001
    beta1: 0.5
    beta2: 0.999

eval_config:
  each_cls: True
  cls_idx: [8, 9]
